# agrifarm/docker-compose.yml
services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ORG: my-org
      DOCKER_INFLUXDB_INIT_BUCKET: my-bucket

  api:
    build:
      context: ./backend
    container_name: agrifarm-api
    ports:
      - "3001:3001"
    depends_on:
      - influxdb

  web:
    build:
      context: ./frontend
    container_name: agrifarm-web
    ports:
      - "3000:80"
    depends_on:
      - api
